version: '3'
services:
  wangy:
    build: .
    restart: unless-stopped
    volumes:
      - "./logs:./logs"
      - ".env:.env"
    networks:
      - wangy-network
      
networks:
  wangy-network:
    driver: overlay
    attachable: true
