version: '3'
services:
  wangy:
    build: .
    restart: unless-stopped
    volumes:
      - "./logs:/app/logs"
      - "./.env:/app/.env"
    networks:
      - wangy-network
      
networks:
  wangy-network:
    driver: bridge
